<?php
/**
 * DriveNow Chatbot API — Sends messages to n8n AI Agent
 *
 * n8n AI Agent uses PostgreSQL Chat Memory node with table: n8n_chat_histories
 * n8n handles conversation history automatically — PHP just proxies messages
 *
 * n8n expects: { chatInput: "user message", sessionId: "unique-session-id" }
 * n8n returns: { output: "bot response" }
 *
 * Retry logic: up to 3 attempts (1 initial + 2 retries) with 1.5s delay.
 * Handles: Gemini API timeouts, empty responses, transient n8n errors.
 */
require_once __DIR__ . '/bootstrap.php';

$input = api_init(['allow_origin' => '*']);

// Load environment variables
require_once __DIR__ . '/../config/env.php';

define('N8N_WEBHOOK_URL', EnvLoader::get('N8N_WEBHOOK_URL'));

// Get input
if (!$input || empty(trim($input['message'] ?? $input['chatInput'] ?? ''))) {
    api_json(['success' => false, 'message' => 'Message is required']);
    exit;
}

$message  = trim($input['message'] ?? $input['chatInput'] ?? '');
$userId   = $_SESSION['user_id'] ?? null;

// ============================================
// Session ID strategy (used by n8n Postgres Chat Memory):
//   Logged-in user  → "user_{userId}"  — stable, same on all devices
//   Anonymous user  → "anon_{uuid}"    — UUID generated by frontend,
//                                         stored in localStorage per browser
// NOTE: never use PHP session_id() — it resets on session expiry
//       and could collapse all anon users onto the same history.
// ============================================
if ($userId) {
    // Authenticated: always derive from user ID so history is consistent
    $chatSessionId = 'privatehire_user_' . $userId;
} else {
    // Anonymous: expect UUID from frontend (localStorage)
    $clientUuid = trim($input['clientSessionId'] ?? '');
    // Validate it looks like a UUID / non-empty safe string
    if (!empty($clientUuid) && preg_match('/^[a-zA-Z0-9\-_]{8,64}$/', $clientUuid)) {
        $chatSessionId = 'privatehire_anon_' . $clientUuid;
    } else {
        // Fallback: generate a random ID (won't persist history across requests
        // but at least won't mix with other users)
        $chatSessionId = 'privatehire_anon_' . bin2hex(random_bytes(12));
    }
}

// ============================================
// Retry configuration
// ============================================
$maxAttempts  = 3;       // 1 initial attempt + up to 2 retries
$retryDelayMs = 1500;    // 1.5 seconds between retries

$n8nPayload = [
    'chatInput' => $message,
    'sessionId' => $chatSessionId,
    'userId'    => $userId,
    'timestamp' => date('c'),
];

$debugLog = __DIR__ . '/../logs/chatbot_debug.log';
$debugDir = dirname($debugLog);
if (!is_dir($debugDir)) @mkdir($debugDir, 0777, true);

$botResponse = null;
$lastError   = null;

for ($attempt = 1; $attempt <= $maxAttempts; $attempt++) {

    // --- Call n8n ---
    $n8nResponse = sendToN8N($n8nPayload);

    // --- n8n connection/HTTP failure ---
    if (!$n8nResponse['success']) {
        $httpCode  = $n8nResponse['http_code'] ?? 0;
        $lastError = "HTTP $httpCode: " . ($n8nResponse['error'] ?? 'unknown error');

        @file_put_contents(
            $debugLog,
            date('[Y-m-d H:i:s]') . " Attempt $attempt/$maxAttempts FAILED — $lastError\n",
            FILE_APPEND
        );

        // 404 = workflow not active — retrying won't help
        if ($httpCode === 404) {
            $lastError = "n8n workflow not found (HTTP 404). Make sure the workflow is Active in n8n.";
            break;
        }

        if ($attempt < $maxAttempts) {
            usleep($retryDelayMs * 1000);
            continue;
        }
        break;
    }

    // --- Parse response ---
    $responseData = $n8nResponse['data'];

    @file_put_contents(
        $debugLog,
        date('[Y-m-d H:i:s]') . " Attempt $attempt/$maxAttempts OK | type=" . gettype($responseData) . " | raw=" . substr(json_encode($responseData, JSON_UNESCAPED_UNICODE), 0, 300) . "\n",
        FILE_APPEND
    );

    // ============================================
    // Extract bot text from various n8n response formats:
    //   "plain text"                    — plain string
    //   { output: "..." }              — AI Agent standard
    //   [{ output: "..." }]            — Webhook-wrapped array
    //   [{ json: { output: "..." } }]  — n8n item format
    //   { data: { output: "..." } }    — nested data key
    // ============================================

    // Format 1: plain string
    if (is_string($responseData) && !empty(trim($responseData))) {
        $botResponse = trim($responseData);
    }

    // Format 2–5: array
    if (!$botResponse && is_array($responseData)) {

        // [{ ... }] or [{ json: { ... } }]
        if (isset($responseData[0]) && is_array($responseData[0])) {
            $item = $responseData[0];
            if (isset($item['json']) && is_array($item['json'])) {
                $item = $item['json'];
            }
            $botResponse = $item['output'] ?? $item['response'] ?? $item['text'] ?? $item['message'] ?? $item['content'] ?? null;
        }

        // { output: "..." } direct
        if (!$botResponse) {
            $botResponse = $responseData['output'] ?? $responseData['response'] ?? $responseData['text'] ?? $responseData['message'] ?? $responseData['content'] ?? null;
        }

        // { data: { output: "..." } }
        if (!$botResponse && isset($responseData['data']) && is_array($responseData['data'])) {
            $d = $responseData['data'];
            $botResponse = $d['output'] ?? $d['response'] ?? $d['text'] ?? $d['message'] ?? null;
        }

        // Last resort: first non-empty string value
        if (!$botResponse) {
            $skipKeys = ['sessionId', 'userId', 'timestamp', 'chatInput'];
            foreach ($responseData as $key => $val) {
                if (is_string($val) && !empty(trim($val)) && !in_array($key, $skipKeys, true)) {
                    $botResponse = trim($val);
                    break;
                }
            }
        }
    }

    // Got a valid response — stop retrying
    if (!empty($botResponse)) {
        break;
    }

    // Empty response — will retry
    $lastError = "empty response from n8n (attempt $attempt)";
    @file_put_contents(
        $debugLog,
        date('[Y-m-d H:i:s]') . " Attempt $attempt/$maxAttempts: empty bot response, retrying...\n",
        FILE_APPEND
    );

    if ($attempt < $maxAttempts) {
        usleep($retryDelayMs * 1000);
    }
}

// ============================================
// Return result
// ============================================
if (!empty($botResponse)) {
    echo json_encode([
        'success'    => true,
        'response'   => $botResponse,
        'session_id' => $chatSessionId,
    ]);
} else {
    @file_put_contents(
        $debugLog,
        date('[Y-m-d H:i:s]') . " ALL $maxAttempts attempts failed. Last error: $lastError\n",
        FILE_APPEND
    );
    echo json_encode([
        'success' => false,
        'message' => 'The assistant is temporarily unavailable. Please try again in a moment.',
    ]);
}

// =====================================================
// HELPER FUNCTIONS
// =====================================================

/**
 * Send request to n8n webhook
 */
function sendToN8N($data) {
    $url = N8N_WEBHOOK_URL;

    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL            => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => json_encode($data),
        CURLOPT_HTTPHEADER     => ['Content-Type: application/json', 'Accept: application/json'],
        CURLOPT_TIMEOUT        => 60,   // AI Agent can take longer to respond
        CURLOPT_CONNECTTIMEOUT => 10,
        CURLOPT_FOLLOWLOCATION => true,
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error    = curl_error($ch);
    curl_close($ch);

    if ($error) {
        return ['success' => false, 'error' => 'cURL error: ' . $error, 'http_code' => 0];
    }

    // Log raw curl response for debugging
    $debugLog = __DIR__ . '/../logs/chatbot_debug.log';
    @file_put_contents(
        $debugLog,
        date('[Y-m-d H:i:s]') . " n8n HTTP $httpCode | URL: $url | Body: " . substr($response, 0, 400) . "\n",
        FILE_APPEND
    );

    if ($httpCode < 200 || $httpCode >= 300) {
        return [
            'success'   => false,
            'error'     => "n8n returned HTTP $httpCode. Response: " . substr($response, 0, 300),
            'http_code' => $httpCode,
        ];
    }

    $decoded = json_decode($response, true);

    return [
        'success'   => true,
        'data'      => $decoded !== null ? $decoded : $response,
        'http_code' => $httpCode,
    ];
}
